version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: melacode44/node-js-sample
    machine:
      - image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: sudo docker build -t $IMAGE_NAME:latest .
      - run:
          name: Testing docker image
          command: docker run --rm -d --name=test -p 8080:8080 $IMAGE_NAME:latest && docker ps --last=1 && curl --retry 12 -v http://0.0.0.0:8080/ ; docker stop test
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
