version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: melacode44/node-js-sample
    machine:
      - image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Testing docker image
          command: docker run --rm -d --name=test -p 8080:8080 $IMAGE_NAME:latest && curl --retry 10 --retry-all-errors --retry-delay 5 -v http://localhost:8080
      #- run:
          #name: Publish Docker Image to Docker Hub
          #command: |
            #echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            #docker push $IMAGE_NAME:latest
